<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.63.0" />
    <PackageReference Include="PW.AutoMapper.Extensions.Protobuf" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProductionRecipes.Application\ProductionRecipes.Application.csproj" />
    <ProjectReference Include="..\ProductionRecipes.Contracts\ProductionRecipes.Contracts.csproj" />
    <ProjectReference Include="..\ProductionRecipes.DataAccess\ProductionRecipes.DataAccess.csproj" />
    <ProjectReference Include="..\ProductionRecipes.Domain\ProductionRecipes.Domain.csproj" />
    <ProjectReference Include="..\ProductionRecipes.GrpcProtos\ProductionRecipes.GrpcProtos.csproj" />
  </ItemGroup>

  <ProjectExtensions><VisualStudio><UserProperties properties_4launchsettings_1json__JsonSchema="" /></VisualStudio></ProjectExtensions>

</Project>
