<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.63.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProductionRecipes.Application\ProductionRecipes.Application.csproj" />
    <ProjectReference Include="..\ProductionRecipes.GrpcProtos\ProductionRecipes.GrpcProtos.csproj" />
  </ItemGroup>

</Project>
