<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GrpcService\ProductionRecipes.Services.csproj" />
    <ProjectReference Include="..\ProductionRecipes.Application\ProductionRecipes.Application.csproj" />
    <ProjectReference Include="..\ProductionRecipes.Contracts\ProductionRecipes.Contracts.csproj" />
    <ProjectReference Include="..\ProductionRecipes.DataAccess\ProductionRecipes.DataAccess.csproj" />
    <ProjectReference Include="..\ProductionRecipes.Domain\ProductionRecipes.Domain.csproj" />
    <ProjectReference Include="..\ProductionRecipes.GrpcProtos\ProductionRecipes.GrpcProtos.csproj" />
  </ItemGroup>

</Project>
